// import { OrdenCompra } from './orden-compra';
import { FrutaVariedad } from '../../maestros/fruta-variedad/fruta-variedad';
import { TablaAuxiliarDetalle } from '../../auxiliares/tabla-auxiliar/models/tabla-auxiliar-detalle';
import { OrdenCompraEmpaquetado } from './orden-compra-empaquetado';
import { Fruta } from '../../maestros/fruta/fruta';

export class OrdenCompraDetalle {
  nro: number = 0;
  id: number;
  //ordenCompra: OrdenCompra;
  fruta: Fruta;
  placeholderFruta: string = "Fruta";
  frutaVariedad: FrutaVariedad;
  categoriaFruta: TablaAuxiliarDetalle;
  procedencia: string='';
  tamanoFruta: TablaAuxiliarDetalle;
  estadoFruta: TablaAuxiliarDetalle;
  observacion: string='';
  unidadCompra: TablaAuxiliarDetalle;
  precioUnitario: number=0;
  placeholderPrecioUnitario: string = "";
  cantidadFruta: number = 0;
  placeholderCantidadFruta: string = "";
  precioTotal: number=0;
  descuento: number = 0.0;
  precioTotalDescuento: number=0;
  igv: number=0;
  precioTotalIgv: number=0;
  formaPago: TablaAuxiliarDetalle;
  fechaPago: Date;
  responsablePago: string='';
  indAdicional: boolean = false;
  tipoAdicional: TablaAuxiliarDetalle;
  cantidadAdicional: number = 0.0;
  indIndividualizar: boolean = false;
  empaques: Array<OrdenCompraEmpaquetado> = [];
  pesoEmpaque: number = 0.0;
  tipoEmpaque: string = '';
  totalEmpaques: number = 0;
  indFinalizadoEmpaque: boolean = false;
  fechaArribo: Date;
  fechaArriboDate: Date;
  fechaArriboTime: String = '';
  indMerma: boolean = false;
  pesoMerma: number = 0.0;
  tipoMerma: string = '';
  archivoFotoEmbalaje: File;
  fotoEmbalaje: string;
  archivoFotoMerma: File;
  fotoMerma: string;
  idUsuarioCrea: number;
  fechaCrea: string;
  idUsuarioModifica: number;
  fechaModifica: string;
  ////
  blnHabilitarBloqueFruta:boolean = true;
  blnHabilitarBloqueCompra:boolean = false;
  blnHabilitarBloqueJavasCompradas:boolean = false;
}
